spring:
  application:
    name: notes-service
  datasource:
    url: jdbc:mysql://localhost:3306/notes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8081